### ISSUE TITLE
Design Docs Review #1 

### ISSUE THREAD

**Issue by jliversi** [Droool/OpenCounter#1]
Really good job so far, just a few a suggestions:

MVP LIST 
- [x] At which point will you build out your restaurant index and show pages? I assume this will be in "Create and search restaurants", so let's be specific there. Additionally, does openTable have the ability for users to create restaurants? If not, let's move this from our MVP list and the main CRUD on your site will be reservations and reviews. 

SCHEMA
- [x] Really good job on your schema. The one thing that's noticeably missing is a `cuisine_id` on your restaurants table.
- [x] Consider adding `lat` and `lon` columns to your restaurants table which can be used to easily render their locations on a google map. 

SAMPLE STATE
- [x] Let's build our site (at least pre-bonus) to be entirely from the customer's experience and not for restaurant owners. As a result, let's remove "restaurantIds" from our users slice of state (and ownerId from our restaurants slice).
- [x] We probably don't need a "favorites" slice of state. Because this is really just a joins table for users/restaurants, we can get away with just storing an array of "favoriteIds" on each user and just use these to reference restaurants in the restaurants slice. 

Overall, really great job, I can tell that you spent a lot of time looking at OpenTable and thinking about implementation.

**Comment by Droool** [comment]
I made the changes to the mvp list and removed the creation of restaurants since it's out of scope at the moment. The project will mainly focus on the user experience.

For the schema, I added cuisine_id, lat, lon. I had forgotten to add `_id` on cuisine but it was available on the table. I also added longitude and latitude coordinates for the map. Will those be considered integer or float type ?

For the sample state, I removed the restaurant owner since creating restaurants is currently out of scope. I also removed the favorite state as it can be an id tied to users as their favorites.

Let me know if there's anything else that needs modifying. Thanks Josh!

**Comment by jliversi** [comment]
Good job on the edits, and on your backend/frontend routes. Just a few notes for your docs and you should have a great roadmap: 

SCHEMA 
- [ ] I took a look at real Open Table and I realized that a restaurant can have multiple cuisines. In this case, we'll probably want to remove cuisine_id from restaurants and instead include a joins table for cuisines/restaurants.

SAMPLE STATE
- [ ] I like that you included a potential restaurant owner for eventual bonuses, but make sure to remove the favorites slice now that we have them referenced from the users slice. Additionally, add a session slice of state to hold reference to your current user. 

BACKEND ROUTES 
- [ ] For our reservations index route, should this be nested for a specific restaurant? If so, should it be `/api/restaurants/:restaurant_id/reservations`? 
- [ ] For reviews, create a nested route `/api/restaurants/:restaurant_id/reviews` which will return the reviews for a specific restaurant. 

FRONTEND ROUTES
- [ ] For all of your routes, be sure to include the components that will render for each route.
- [ ] Will we need a separate route for a restaurants reviews? It seems to me that this is just another component on the page for a restaurant.

**Comment by Droool** [comment]
I've gone ahead and made the changes in the wiki. I'm still shaky on the front end routes but I made some adjustments and added the components you had asked. Please let me know if this is works
